# Site settings
name: 翻山越岭遇到一条狗的Blog
email: 312339704@QQ.COM
author: Kisn
url: http://www.kisnn.cn
resume_site: https://kisnnnnn.github.io/kisnStudy/
github: https://github.com/Kisnnnnn/
description: 「今でもあなたはわたしの光」
meta_description: 袁凯忻;个人博客;前端技术;
motto: 「今でもあなたはわたしの光」
banner: Be patient，Keep carefu，Independence

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kisnnnnn

# Build settings
markdown: kramdown

# baidu_analysis: 

